volumes:
  dialogflow_cx_chatwoot_data: {}

services:
  bot:
    build: .
    environment:
      PROJECT_ID: "your-project-id"
      AGENT_ID: "your-agent-id"
      CHATWOOT_API_KEY: "your-chatwoot-api-key"
      CHATWOOT_URL: "https://your-chatwoot-instance"
      GOOGLE_APPLICATION_CREDENTIALS: "/config/.dialogflow_service_account.json"
    volumes:
      - dialogflow_cx_chatwoot_data:/app/config
    env_file:
      - ./config/.env
    #ports:
    #  - "4567:4567"
